-- ============================================================
-- CHATFY - Seed: Default Themes Only
-- No products, flows, orders, or deliverables
-- ============================================================

INSERT INTO public.themes (id, name, description, config, is_system) VALUES
(
  'dark_premium',
  'Dark Premium',
  'Tema escuro tecnológico com glassmorphism e gradiente ciano/roxo',
  '{
    "background": "linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)",
    "chatContainer": "rgba(255,255,255,0.05)",
    "chatContainerBorder": "rgba(255,255,255,0.1)",
    "assistantBubble": "rgba(255,255,255,0.08)",
    "assistantBubbleBorder": "rgba(255,255,255,0.15)",
    "assistantText": "#E2E8F0",
    "userBubble": "linear-gradient(135deg, #8B5CF6 0%, #06B6D4 100%)",
    "userText": "#FFFFFF",
    "button": "linear-gradient(135deg, #8B5CF6 0%, #06B6D4 100%)",
    "buttonText": "#FFFFFF",
    "buttonHover": "linear-gradient(135deg, #7C3AED 0%, #0891B2 100%)",
    "headerBg": "rgba(0,0,0,0.4)",
    "headerText": "#FFFFFF",
    "inputBg": "rgba(255,255,255,0.05)",
    "inputBorder": "rgba(255,255,255,0.2)",
    "inputText": "#FFFFFF",
    "scrollbar": "#8B5CF6",
    "typingDot": "#8B5CF6",
    "borderRadius": "16px",
    "bubbleRadius": "18px",
    "shadow": "0 25px 50px rgba(0,0,0,0.5)",
    "fontFamily": "Inter, sans-serif",
    "backdropFilter": "blur(20px)"
  }',
  true
),
(
  'whatsapp_inspired',
  'WhatsApp Inspired',
  'Tema inspirado em conversas de aplicativos de mensagem, com visual familiar de chat',
  '{
    "background": "#ECE5DD",
    "backgroundPattern": "whatsapp_dots",
    "chatContainer": "#FFFFFF",
    "chatContainerBorder": "transparent",
    "assistantBubble": "#FFFFFF",
    "assistantBubbleBorder": "transparent",
    "assistantText": "#303030",
    "userBubble": "#DCF8C6",
    "userText": "#303030",
    "button": "#25D366",
    "buttonText": "#FFFFFF",
    "buttonHover": "#1EBE5A",
    "headerBg": "#128C7E",
    "headerText": "#FFFFFF",
    "inputBg": "#FFFFFF",
    "inputBorder": "#E0E0E0",
    "inputText": "#303030",
    "scrollbar": "#25D366",
    "typingDot": "#8C8C8C",
    "borderRadius": "0px",
    "bubbleRadius": "8px",
    "shadow": "0 1px 3px rgba(0,0,0,0.12)",
    "fontFamily": "Inter, sans-serif",
    "backdropFilter": "none",
    "assistantBubbleShadow": "0 1px 0.5px rgba(0,0,0,0.13)",
    "timestamp": "#8C8C8C"
  }',
  true
),
(
  'instagram_dm_inspired',
  'Instagram DM Inspired',
  'Tema inspirado em DMs modernos com visual mobile, bolhas limpas e gradientes suaves',
  '{
    "background": "#FAFAFA",
    "chatContainer": "#FFFFFF",
    "chatContainerBorder": "#DBDBDB",
    "assistantBubble": "#EFEFEF",
    "assistantBubbleBorder": "transparent",
    "assistantText": "#262626",
    "userBubble": "linear-gradient(135deg, #833AB4 0%, #FD1D1D 50%, #FCB045 100%)",
    "userText": "#FFFFFF",
    "button": "linear-gradient(135deg, #833AB4 0%, #FD1D1D 100%)",
    "buttonText": "#FFFFFF",
    "buttonHover": "linear-gradient(135deg, #6B2FA0 0%, #E01515 100%)",
    "headerBg": "#FFFFFF",
    "headerText": "#262626",
    "inputBg": "#FAFAFA",
    "inputBorder": "#DBDBDB",
    "inputText": "#262626",
    "scrollbar": "#833AB4",
    "typingDot": "#8E8E8E",
    "borderRadius": "0px",
    "bubbleRadius": "22px",
    "shadow": "0 0 0 1px rgba(0,0,0,0.06)",
    "fontFamily": "Inter, sans-serif",
    "backdropFilter": "none"
  }',
  true
),
(
  'minimal_chat',
  'Minimal Chat',
  'Tema limpo, direto e sem distração, ideal para conversão rápida',
  '{
    "background": "#FFFFFF",
    "chatContainer": "#FFFFFF",
    "chatContainerBorder": "#E5E7EB",
    "assistantBubble": "#F3F4F6",
    "assistantBubbleBorder": "transparent",
    "assistantText": "#111827",
    "userBubble": "#111827",
    "userText": "#FFFFFF",
    "button": "#111827",
    "buttonText": "#FFFFFF",
    "buttonHover": "#374151",
    "headerBg": "#FFFFFF",
    "headerText": "#111827",
    "inputBg": "#F9FAFB",
    "inputBorder": "#D1D5DB",
    "inputText": "#111827",
    "scrollbar": "#9CA3AF",
    "typingDot": "#6B7280",
    "borderRadius": "0px",
    "bubbleRadius": "8px",
    "shadow": "0 1px 3px rgba(0,0,0,0.1)",
    "fontFamily": "Inter, sans-serif",
    "backdropFilter": "none"
  }',
  true
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  config = EXCLUDED.config;
