export const systemThemes = [
  {
    id: 'whatsapp',
    name: 'WhatsApp Classic',
    description: 'Interface inspirada em conversa mobile nativa, com fundo suave, bolhas compactas e atendimento conversacional.',
    is_system: true,
    config: {
      background: '#EFEAE2',
      backgroundPattern: 'radial-gradient(circle at 12px 12px, rgba(17,27,33,0.045) 1.1px, transparent 1.3px)',
      chatContainer: '#EFEAE2',
      chatContainerBorder: 'transparent',
      assistantBubble: '#FFFFFF',
      assistantBubbleBorder: 'transparent',
      assistantText: '#111B21',
      userBubble: '#D9FDD3',
      userText: '#111B21',
      button: '#008069',
      buttonText: '#FFFFFF',
      buttonHover: '#017561',
      headerBg: '#008069',
      headerText: '#FFFFFF',
      inputBg: '#FFFFFF',
      inputBorder: '#D1D7DB',
      inputText: '#111B21',
      scrollbar: '#008069',
      typingDot: '#667781',
      borderRadius: '0px',
      bubbleRadius: '8px',
      shadow: '0 1px 0.5px rgba(11,20,26,.13)',
      fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      backdropFilter: 'none',
      timestamp: '#667781',
    },
  },
  {
    id: 'instagram',
    name: 'Instagram DM',
    description: 'Tema claro inspirado em DMs modernas, com header de perfil, bolhas leves e input estilo Direct.',
    is_system: true,
    config: {
      background: '#FFFFFF',
      backgroundPattern: 'none',
      chatContainer: '#FFFFFF',
      chatContainerBorder: '#DBDBDB',
      assistantBubble: '#EFEFEF',
      assistantBubbleBorder: 'transparent',
      assistantText: '#262626',
      userBubble: 'linear-gradient(135deg, #833AB4 0%, #FD1D1D 55%, #FCAF45 100%)',
      userText: '#FFFFFF',
      button: '#0095F6',
      buttonText: '#FFFFFF',
      buttonHover: '#1877F2',
      headerBg: '#FFFFFF',
      headerText: '#262626',
      inputBg: '#FFFFFF',
      inputBorder: '#DBDBDB',
      inputText: '#262626',
      scrollbar: '#0095F6',
      typingDot: '#8E8E8E',
      borderRadius: '0px',
      bubbleRadius: '18px',
      shadow: 'none',
      fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      backdropFilter: 'none',
      timestamp: '#8E8E8E',
    },
  },
  {
    id: 'minimal_chat',
    name: 'Minimal Tech',
    description: 'Tema tecnológico claro, com estética limpa, tons frios, linhas finas e foco em leitura.',
    is_system: true,
    config: {
      background: '#F6F8FB',
      backgroundPattern: 'linear-gradient(rgba(15,23,42,0.035) 1px, transparent 1px), linear-gradient(90deg, rgba(15,23,42,0.035) 1px, transparent 1px)',
      chatContainer: '#F6F8FB',
      chatContainerBorder: 'rgba(15,23,42,0.08)',
      assistantBubble: '#FFFFFF',
      assistantBubbleBorder: '#E2E8F0',
      assistantText: '#0F172A',
      userBubble: '#DBEAFE',
      userText: '#0F172A',
      button: '#2563EB',
      buttonText: '#FFFFFF',
      buttonHover: '#1D4ED8',
      headerBg: 'rgba(248,250,252,0.94)',
      headerText: '#0F172A',
      inputBg: '#FFFFFF',
      inputBorder: '#CBD5E1',
      inputText: '#0F172A',
      scrollbar: '#2563EB',
      typingDot: '#64748B',
      borderRadius: '0px',
      bubbleRadius: '12px',
      shadow: '0 10px 28px rgba(15,23,42,0.08)',
      fontFamily: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      backdropFilter: 'blur(18px)',
      timestamp: '#64748B',
    },
  },
  {
    id: 'dark_premium',
    name: 'Dark Command',
    description: 'Tema tecnológico escuro, com contraste alto, brilho ciano discreto e sensação de painel operacional.',
    is_system: true,
    config: {
      background: '#070D1A',
      backgroundPattern: 'radial-gradient(circle at 20% 20%, rgba(34,211,238,0.12), transparent 28%), linear-gradient(rgba(34,211,238,0.035) 1px, transparent 1px), linear-gradient(90deg, rgba(34,211,238,0.035) 1px, transparent 1px)',
      chatContainer: '#0B1220',
      chatContainerBorder: 'rgba(34,211,238,0.18)',
      assistantBubble: '#101827',
      assistantBubbleBorder: 'rgba(34,211,238,0.18)',
      assistantText: '#E5F7FF',
      userBubble: '#123D4A',
      userText: '#E6FFFB',
      button: '#22D3EE',
      buttonText: '#041016',
      buttonHover: '#67E8F9',
      headerBg: 'rgba(7,13,26,0.92)',
      headerText: '#E5F7FF',
      inputBg: '#0F172A',
      inputBorder: 'rgba(34,211,238,0.24)',
      inputText: '#E5F7FF',
      scrollbar: '#22D3EE',
      typingDot: '#67E8F9',
      borderRadius: '0px',
      bubbleRadius: '12px',
      shadow: '0 12px 34px rgba(0,0,0,0.34)',
      fontFamily: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      backdropFilter: 'blur(18px)',
      timestamp: '#8FB6C5',
    },
  },
]
